apply from: gradle.ext.sharedModulesConstants
apply plugin: 'com.android.library'

android {
    compileSdkVersion project.ext.compileSdkVersion
    buildToolsVersion project.ext.buildToolsVersion

    defaultConfig {
        minSdkVersion project.ext.minSdkVersion
        targetSdkVersion project.ext.targetSdkVersion
        versionCode 1
        versionName '0.4.1'
        consumerProguardFiles 'proguard.txt'
        multiDexEnabled true
    }
    android {
        lintOptions {
            abortOnError false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation project(':sharedutils')

    implementation 'androidx.appcompat:appcompat:' + appCompatXVersion
    implementation 'com.google.android.material:material:' + materialVersion
    implementation "com.google.android.flexbox:flexbox:" + flexboxVersion
    implementation 'androidx.recyclerview:recyclerview:' + recyclerviewXVersion
}
